client: client_main.cpp client.cpp utils.cpp
	g++ -g -Wall -Werror -std=c++20 client_main.cpp utils.cpp client.cpp -o client

server: server_main.cpp server.cpp utils.cpp
	g++ -g -Wall -Werror -std=c++20 server_main.cpp utils.cpp server.cpp -o server

clean:
	rm client server